### PR TITLE
Jdbc-databse-connectivity

### PR DESCRIPTION
**Pull request by godsakani**
Completed task for JDBC connectivity.
please your QA will help

### CODE REVIEW

**Review by andrew21-mch — APPROVED** [review]
Its good 
you could also trying updating it so the createData methods takes in some parameters and operates based on the parameters

this could be applicable for both the update and delete methods

**Review by andrew21-mch — APPROVED** [review]
Its good 
you could also trying updating it so the createData methods takes in some parameters and operates based on the parameters

this could be applicable for both the update and delete methods

**Comment by godsakani** [comment]
> Its good you could also trying updating it so the createData methods takes in some parameters and operates based on the parameters
> 
> this could be applicable for both the update and delete methods

ok

**Comment by godsakani** [comment]
> Its good you could also trying updating it so the createData methods takes in some parameters and operates based on the parameters
> 
> this could be applicable for both the update and delete methods

ok

**Pull request merged**
